[package]
name = "tsc"
version = "0.1.0"
edition = "2021"

[dependencies]
#rssc = { git  = "https://github.com/stuartcalder/rssc.git" }
rssc  = { path = "../rssc" }

[lib]
name = "tsc"
path = "src/lib.rs"

[features]
default = ["C_alignas"]
C_alignas = []
